[package]
name = "stabilizer-streaming"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.5"
num_enum = "0.5"
log = "0.4"
env_logger = "0.9"
async-std = { version = "1", features = ["attributes"] }
std-embedded-nal = "0.1"
std-embedded-time = "0.1"
minimq = "0.4"
serde_json = "1"
serde = {version = "1", features = ["derive"]}
uuid = {version = "0.8", features = ["v4"]}
